auto_docking:
  kp:
    x:           0.3
    y:           1.5
    theta:       0.5
    x_fine:      0.5
    y_fine:      3.0
    theta_fine:  0.2
  velocity:
    linear:
      x:
        max:     5
        min:     0.15
      y:
        max:     5
        min:     0.15
    angular:
        min:     0.02
  tolerance:
    y:           0.003
  